---
- name: Gather swap status
  command: sudo swapon --show
  register: swap_status
  changed_when: false
  ignore_errors: true

- name: Turn off swap
  command: sudo swapoff -a
  when: swap_status.stdout_lines | length > 0

- name: Remove swap from fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^.*swap.*$'
    state: absent

