- name: Gather current kernel command line
  command: cat /boot/firmware/cmdline.txt
  register: ansible_facts_cmdline
  changed_when: false
  become: yes

- name: Set cmdline fact
  set_fact:
    ansible_facts:
      cmdline: "{{ ansible_facts_cmdline }}"

- name: Append cgroups settings if missing
  lineinfile:
    path: /boot/firmware/cmdline.txt
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    backrefs: yes
    state: present
  become: yes
  loop:
    - { line: '\1 cgroup_enable=cpuset', regexp: '^(.*[^ ])$', check: "cgroup_enable=cpuset" }
    - { line: '\1 cgroup_memory=1', regexp: '^(.*[^ ])$', check: "cgroup_memory=1" }
    - { line: '\1 cgroup_enable=memory', regexp: '^(.*[^ ])$', check: "cgroup_enable=memory" }
  when:
    - ansible_architecture == "aarch64" or ansible_architecture == "armv7l"
    - item.check not in cmdline.stdout
  notify: Reboot node
