- name: Gather current kernel command line
  command: cat /boot/firmware/cmdline.txt
  register: ansible_facts_cmdline
  changed_when: false

- name: Set cmdline fact
  set_fact:
    ansible_facts:
      cmdline: "{{ ansible_facts_cmdline }}"
