---
- name: Reboot node
  reboot:
    msg: "Reboot initiated by Ansible due to cgroups changes"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
  become: yes

- name: Restart k3s
  systemd:
    name: k3s
    state: restarted
  become: yes
