- name: check availability on all servers
  hosts: k3s_nodes
  tasks:
    - name: ping my hosts
      ansible.builtin.ping:

    - name: print message
      ansible.builtin.debug:
        msg: Hello World!
